getPlatformString
openframeworks/projectGenerator pull request #509
Opened 2024-05-28 23:02 UTC by dimitre

This PR adds the special function getPlatformString for PG
it returns the actual development platform you are using. you can develop on macOS but not on iOS, you will be able to run project generator in Raspberry PI but not on Android.

2024-06-04 08:48 UTC, danoli3 commented
This is good! I think we should allow this setting in advanced options too directly

2024-07-16 10:11 UTC, danoli3 requested changes
And rebase and stuff and lets get this in

2024-07-16 10:11 UTC, danoli3 commented on commandLine/src/projects/baseProject.h
> +#define PG_VERSION "42"
this gonna conflict

2024-07-16 10:11 UTC, danoli3 commented on commandLine/src/utils/Utils.cpp
> +std::string exec(const char* cmd) {
can we call this execute_popen

2024-07-16 13:03 UTC, dimitre commented on commandLine/src/utils/Utils.cpp
> +std::string exec(const char* cmd) {
sure thing

2024-07-16 13:06 UTC, dimitre commented
@danoli3 ok all updated and compiling.

2024-07-16 15:22 UTC, danoli3 commented
oh wait what happened to linux and windows,

2024-07-16 18:19 UTC, danoli3 commented
shall merge tomorrow

2024-08-23 21:08 UTC, dimitre commented
merge master, fix conflicts, version bump. good to go @danoli3

2024-08-24 03:41 UTC, merged